# Generated by Django 5.1.6 on 2026-02-28 21:47

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='event_covers/%Y/%m/')),
                ('event_type', models.CharField(choices=[('in_person', 'In Person'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='in_person', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Null means unlimited capacity.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_private', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False, help_text='If True, registrations start as pending until manually approved.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', 'Host'), ('co_host', 'Co-host'), ('speaker', 'Speaker'), ('volunteer', 'Volunteer'), ('moderator', 'Moderator')], max_length=10)),
                ('bio_override', models.TextField(blank=True, help_text='Event-specific bio shown on the event page (e.g. speaker intro).')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('interval', models.PositiveSmallIntegerField(default=1, help_text='Repeat every N frequency units (e.g. every 2 weeks).')),
                ('by_weekday', models.CharField(blank=True, max_length=20)),
                ('by_month_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of month (1–31) for monthly recurrence.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Recurrence ends on this date. Null means indefinite.', null=True)),
                ('max_occurrences', models.PositiveSmallIntegerField(blank=True, help_text='Stop after N occurrences. Takes precedence over end_date.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
