# Generated by Django 5.1.5 on 2025-01-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('interested', 'Insterested'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='interested', max_length=10),
        ),
    ]
