# Generated by Django 5.1.6 on 2026-02-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('event_invite', 'Event Invitation'), ('event_update', 'Event Updated'), ('event_cancelled', 'Event Cancelled'), ('reg_confirmed', 'Registration Confirmed'), ('reg_pending', 'Registration Pending'), ('new_follower', 'New Follower'), ('org_invite', 'Organization Invitation'), ('comment_reply', 'Reply to Comment'), ('reminder', 'Event Reminder')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
